### ISSUE TITLE
Support running earthly rootless

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#1144]
Currently Earthly starts a buildkit daemon in privileged mode. This is oftentimes incompatible with some CI environments (and also with k8s) which do not allow privileged operation.

An alternative to using the unprivileged environment of the CI the user can opt to connect to a [remote buildkit instance](https://docs.earthly.dev/ci-integration/remote-buildkit). However, this requires that the user runs and operates such an instance on their own.

It would be useful to support rootless mode in Earthly (a feature that already exists in buildkit - it just needs to be ported). This should additionally make any `WITH DOCKER` instances used within builds also rootless.

**Comment by frafra** [comment]
Discussion on Slack: https://earthlycommunity.slack.com/archives/C01DL2928RM/p1648817327602409

# Workaround

`Earthfile`:
```Dockerfile
test:
    #[...]
    RUN --secret KEY1 --secret KEY2 echo "KEY1=${KEY1}\nKEY2=${KEY2}" > .env
    SAVE ARTIFACT .env .
    SAVE IMAGE myproject:test

test-local:
    LOCALLY
    COPY +test/.env .
    RUN docker-compose run --rm myproject:test ; docker-compose down -v ; rm .env
```

`docker-compose.yml`:
```yaml
version: "3"
services:
  myproject:
    image: myproject:test
    command: pytest --cov=modules tests    
    environment:
      KEY1: ${KEY1}
      KEY2: ${KEY2}
    depends_on:
      - postgres
    volumes:
      - .:/app
  postgres:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
```

## Notes

### .env is necessary
See #1800.

### .env has to be removed at the end
I have no idea why, but this happens otherwise:
```
Error: secret "KEY1" already contains a value
```

### Cannot have a single target
`LOCALLY` needs to be the first instruction, as it replaces `FORM`.

### An artifact needs to be produced
It is not possible to use `BUILD` together with `LOCALLY` (as the documentation says), so even if `.env` is not needed, using `COPY` seems to be the only way to trigger the `test` stage implicitly.
