### ISSUE TITLE
SSH substitute example does not work due to slash

### ISSUE THREAD

**Issue by wijnanjo** [earthly/earthly#1489]
The documentation on "Authenticating Git and Image registries" contains the following sample:

```
git:
    ghe.internal.mycompany.com:
        pattern: 'ghe.internal.mycompany.com/([^/]+)/([^/]+)'
        substitute: 'ssh://git@ghe.internal.mycompany.com:22/\$1/\$2.git'
        auth: ssh
```

When I base my specific config on that example (and start ssh-agent and do ssh-add), then I cannot do IMPORT statements from git. This is a self managed GitLab instance. This is the error:
`Error: build target: build main: bkClient.Build: failed to solve: failed to load cache key: failed to fetch remote ssh://xxxxx@mobi-git.ktr.kontron.com:22/%5Clfc-devops/%5Clfc-deploy.git: exit status 2`

However, when I update my earthly config.yml and simply remove the 2 backslashes on the replacement vars ($1 and $2), it all works.
Detail: use  ```/$1/$2.git``` instead of ```/\$1/\$2.git```

I'm testing this on a WSL2 environment.
