### ISSUE TITLE
Earthly and Skaffold

### ISSUE THREAD

**Issue by kodeninja** [earthly/earthly#1508]
We currently leverage [`skaffold`](https://skaffold.dev/) to build and deploy docker images in our GitLab CI.

Is there any guidance on how `earthly` would be integrated in this setup? Would it replace only the _build_ part of the process?

```yaml
build:
  stage: build
  tags: [ dind ]
  services:
    - docker:stable-dind
  script:
    - skaffold build --profile $SKAFFOLD_PROFILE --file-output=tags.json
  retry: 2
  when: on_success
  artifacts:
    paths:
      - tags.json
```

```yaml
deploy:
  stage: deploy
  script:
    - skaffold render --digest-source=none --profile $SKAFFOLD_PROFILE --build-artifacts=tags.json
    - skaffold deploy --skip-render=false --force=true --profile $SKAFFOLD_PROFILE --build-artifacts=tags.json
  retry: 2
  when: on_success
```

**Comment by alexcb** [comment]
> Would it replace only the build part of the process?

That seems correct, earthly is able to build (and push) docker images, but doesn't perform kubernetes deploys.

You might be able to replace your `build` with something similar to

```
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.2
      - uses: actions/checkout@v2
      - name: build with earthly
        run: earthly +your-target
```
