### ISSUE TITLE
CACHE command to support shared remote caches

### ISSUE THREAD

**Issue by brandonSc** [earthly/earthly#1540]
# Remote cache support

Currently the CACHE command only works with local cache, however, supporting remote cache would allow multiple users to share the same cache between runs. This may be intuitive to users who are familiar with using the more general [shared remote cache](https://docs.earthly.dev/docs/guides/shared-cache) feature.

## Prerequisite (Phase I)

Phase I of the `CACHE` command feature is implemented in https://github.com/earthly/earthly/issues/1399. 

Consider the following example:

```Earthfile
one:
      FROM alpine
      CACHE /path/to/cache
      RUN touch /path/to/cache/one
      # at this point earthly copies the contents of the cache into /path/to/cache in the image,
      # which makes it available to anyone inheriting this image (or if the image is pushed to a registry)
two:
      from +one
      # cached file is available here, thanks to --persist
      RUN ls /path/to/cache/one
```

We will extend this above example using remote cache as describe below.

## `--load` Flag (Phase II)

Note: the explicit `--load` flag may not be required and may just work automatically when shared cache is [provided via command-line](https://docs.earthly.dev/docs/guides/shared-cache) (TBD).

If you are using a [shared remote cache](https://docs.earthly.dev/docs/guides/shared-cache) and persisting the cache into either the inline cache or the explicit cache then it should be possible to share this cache remotely. 

```
earthly --remote-cache=mycompany/myimage:cache  --load +some-target
```
Doing this with an earthfile with the above CACHE statement `CACHE /path/to/cache` would cause earthly to initially load the cache volume `/path/to/cache` from the contents of the remote image. 

This would allow developers to share a maven cache, dialyzer files, or other intermediate results among the team. 

Open Questions:
* Should `--load` be on by default with `--remote-cache` (or `--ci`)?
* Can we come up with a better name for `--load`?

## Phase III and Beyond

There are several other possible additions to the CACHE keyword that could increase build performance but tradeoff the hermetic and repeatable nature of earthly builds :

- Allow sharing of cache volumes between targets
  - Possible challenges: parallelization is harder to control. What happens when distinct, parallel targets use the same cache volume.
- Allow local bind mount, or pre-populating the cache with the contents of a local directory
  - Possible challenges: the Earthfile depends on local directory layout, which makes the build less repeatable. Perhaps this is an earthly command-line instruction (e.g. `earthly --local-cache=maven=/home/jack/.m2` and the Earthfile has a `CACHE id=maven /path/to/target` somewhere).

We want to gather more use cases for these and get feedback on phases I and II before committing to these.

**Comment by mattste** [comment]
I ran into something that I believe is related to this feature.

### Use Case
I'm attempting to do pull request previews where each pull request has its own Docker image. For pull requests that update a dependency (such as a package.json or mix.lock), these builds can be super slow. 

### Current Options

#### Per-branch cache
The suggested fix would be to have the pull request's branch use its own cache instead of using the `main` branch cache. `earthly --remote-cache=[us-west1-docker.pkg.dev/my-org/my-repo/build-cache:cache-$branch-name-v1](http://us-west1-docker.pkg.dev/my-org/my-repo/build-cache:cache-$branch-name-v1) --push +build`. 

The downside of this approach is that it can be very slow for the very first commit's build as it has to start from nothing.

### CircleCI Approach
On CircleCI, we can do the following:
```
- restore_cache:  # restores saved mix cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:  # list of cache keys, in decreasing specificity
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:  # restores saved build cache
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, compile  # get updated dependencies & compile them
 ```
This can speed up builds dramatically.

### Conclusion
I'd love to see Earthly better handle this use case. I'm not sure how to have this play nicely with `CACHE` and `--remote-cache`.

For more information, see [this Slack thread](https://earthlycommunity.slack.com/archives/C01DL2928RM/p1645648776482129)
