### ISSUE TITLE
WITH DOCKER use causing rm: can't remove /var/earthly/dind....: Resource busy

### ISSUE THREAD

**Issue by willysamz** [earthly/earthly#1647]
### Setups Tried:
- Jenkins running in EKS with k8s plugin & separate earthlly/buildkitd deployment (taken from the docs)
- Jenkins running in EKS with k8s plugin & single pod with both earthly/buildkitd & custom container with Earthly installed (will post this info if requested)

### Versions
Earthly v0.6.6, buildkitd/earthly v0.6.6
Docker Version from inside custom image with earthly installed
```
Client: Docker Engine - Community
 Version:           19.03.15
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        99e3ed8919
 Built:             Sat Jan 30 03:17:11 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.14
  Git commit:       b0f5bc3
  Built:            Wed Nov 17 03:06:14 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0
  GitCommit:        84113eef6fc27af1b01b3181f31bbaf708715301
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
### Custom image with Earthly installed which is used by the Jenkins plugin to run Earthly commands inside of
```yaml
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: earthly
    image: ...customimage:tag
    command:
    - cat
    tty: true
    volumeMounts:
    - name: docker
      mountPath: '/var/run/docker.sock'
    - mountPath: /tmp/earthly
      name: buildkitd-temp
    securityContext:
      privileged: true
    resources:
      limits:
        memory: "768Mi"
        cpu: 2
      requests:
        memory: "512Mi"
        cpu: 2
    env:
      - name: BUILDKIT_HOST
        value: "tcp://earthly-buildkitd.buildkit.svc.cluster.local:8372"
      - name: EARTHLY_BUILDKIT_HOST
        value: "tcp://earthly-buildkitd.buildkit.svc.cluster.local:8372"
   volumes:
  - name: docker
    hostPath:
      path: '/var/run/docker.sock'
  - name: buildkitd-temp
    emptyDir: {}
```       
### Earthly/buildkit k8s deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: earthly-buildkitd
  labels:
    app: earthly
    component: buildkitd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: earthly
      component: buildkitd
  template:
    metadata:
      labels:
        app: earthly
        component: buildkitd
    spec:
      containers:
      - name: buildkitd
        image: earthly/buildkitd:v0.6.6
        # Earthly's buildkit daemon does not currently support rootless modes.
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /tmp/earthly
            name: buildkitd-temp
        env:
          # This needs to be on to allow remote Earthly clients.
          - name: BUILDKIT_TCP_TRANSPORT_ENABLED
            value: 'true'
          # This should be enabled, and certificates configured in a production environment.
          - name: BUILDKIT_TLS_ENABLED
            value: 'false'
          - name: EARTHLY_TMP_DIR
            value: '/tmp/earthly'
      volumes:
        - name: buildkitd-temp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: earthly-buildkitd
  labels:
    app: earthly
    component: buildkitd
spec:
  selector:
    app: earthly
    component: buildkitd
  # Use session affinity to prevent "roaming" across multiple buildkit instances; if needed.
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 6000 # This should be longer than your build.
  ports:
    - protocol: TCP
      port: 8372
      targetPort: 8372
```

### Example Earthfile
```earthly
VERSION 0.6

smoke-test:
    FROM earthly/dind:alpine
    WITH DOCKER --load test:latest=+build-image
        RUN echo "hello"
    END

build-image:
        ARG DOCKER_FILE_PATH="."
        ARG --required IMAGE_NAME
        ARG --required IMAGE_TAG
        ARG --required BUILD_IMAGE
        ARG --required RUNTIME_IMAGE
        ARG --required REGISTRIES

        FROM DOCKERFILE $DOCKER_FILE_PATH --BUILD_IMAGE=$BUILD_IMAGE --RUNTIME_IMAGE=$RUNTIME_IMAGE

        FOR --sep=, registry IN $REGISTRIES
                SAVE IMAGE --push $registry/$IMAGE_NAME:$IMAGE_TAG
        END
```
### Result
```
    ongoing | +smoke-test (13 seconds ago)
         +smoke-test | Loaded image: test:latest
         +smoke-test | ...done
         +smoke-test | hello
         +smoke-test | rm: can't remove '/var/earthly/dind/65825b1ed37d0a16488a77fb8642bbb4cbc3662733d5fe4053c403b8c5dc5641': Resource busy
         +smoke-test | ERROR: Command exited with non-zero code: WITH DOCKER RUN --privileged echo "hello"

============================ ❌ FAILURE [2. Build 🔧] ============================

Repeating the output of the command that caused the failure
         +smoke-test *failed* | --> WITH DOCKER RUN --privileged echo "hello"
         +smoke-test *failed* | Loading images...
         +smoke-test *failed* | Loaded image: test:latest
         +smoke-test *failed* | ...done
         +smoke-test *failed* | hello
         +smoke-test *failed* | rm: can't remove '/var/earthly/dind/65825b1ed37d0a16488a77fb8642bbb4cbc3662733d5fe4053c403b8c5dc5641': Resource busy
         +smoke-test *failed* | ERROR: Command exited with non-zero code: WITH DOCKER RUN --privileged echo "hello"
Error: build target: build main: bkClient.Build: failed to solve: process "/bin/sh -c EARTHLY_DOCKERD_DATA_ROOT=\"/var/earthly/dind/65825b1ed37d0a16488a77fb8642bbb4cbc3662733d5fe4053c403b8c5dc5641\" EARTHLY_DOCKER_LOAD_FILES=\"/var/earthly/load-0/image.tar\" EARTHLY_START_COMPOSE=\"false\" EARTHLY_COMPOSE_FILES=\"\" EARTHLY_COMPOSE_SERVICES=\"\" DIND_COMMIT=42b1175eda071c0e9121e1d64345928384a93df1 DOCKER_TLS_CERTDIR=/certs DOCKER_VERSION=20.10.12 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /var/earthly/dockerd-wrapper.sh execute /usr/bin/earth_debugger /bin/sh -c 'echo \"hello\"'" did not complete successfully: exit code: 1
```
