### ISSUE TITLE
Multiple Priority Ordered Caches

### ISSUE THREAD

**Issue by adamgordonbell** [earthly/earthly#1693]
Currently, when using explicit cache a single cache image can be specified to read from. It could be useful to have a priority-ordered list of images to check for cache hits. @mattste provided this use case:

## Use Case
I'm attempting to do pull request previews where each pull request has its own Docker image. For pull requests that update a dependency (such as a package.json or mix.lock), these builds can be super slow.

## Current Options
Per-branch cache
The suggested fix would be to have the pull request's branch use its own cache instead of using the main branch cache. earthly --remote-cache=[us-west1-docker.pkg.dev/my-org/my-repo/build-cache:cache-$branch-name-v1](http://us-west1-docker.pkg.dev/my-org/my-repo/build-cache:cache-$branch-name-v1) --push +build.

The downside of this approach is that it can be very slow for the very first commit's build as it has to start from nothing.

CircleCI Approach
On CircleCI, we can do the following:
```
- restore_cache:  # restores saved mix cache
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:  # list of cache keys, in decreasing specificity
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:  # restores saved build cache
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, compile  # get updated dependencies & compile them
```
This can speed up builds dramatically.

Conclusion
I'd love to see Earthly better handle this use case. I'm not sure how to have this play nicely with CACHE and --remote-cache.

For more information, see [this Slack thread](https://earthlycommunity.slack.com/archives/C01DL2928RM/p1645648776482129)
