### ISSUE TITLE
`earthly config global` doesn't keep newlines

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#1764]
consider:

```
echo "$GLOBAL_CONFIG"
{disable_analytics: true, local_registry_host: 'tcp://127.0.0.1:8371', conversion_parallelism: 5, buildkit_additional_config: '[registry."docker.io"]
  mirrors = ["192.168.0.80:5000"]
[registry."192.168.0.80:5000"]
  http = true
  insecure = true'}
```

```
> foo.yml
earthly --config foo.yml config global "$GLOBAL_CONFIG"
```

then run `cat foo.yml`, to see:

```
global:
    disable_analytics: true
    local_registry_host: tcp://127.0.0.1:8371
    conversion_parallelism: 5
    buildkit_additional_config: '[registry."docker.io"] mirrors = ["192.168.0.80:5000"] [registry."192.168.0.80:5000"] http = true insecure = true'
```

instead it should be

```
global:
    disable_analytics: true
    local_registry_host: tcp://127.0.0.1:8371
    conversion_parallelism: 5
    buildkit_additional_config: '[registry."docker.io"]
  mirrors = ["192.168.0.80:5000"]
[registry."192.168.0.80:5000"]
  http = true
  insecure = true'
```
