### ISSUE TITLE
Push to Dockerhub auth fails despite Gitlab Actions runner logging in sucessfully

### ISSUE THREAD

**Issue by Oddiesea** [earthly/earthly#1997]
Attempting to push an image from Github Actions to the repo of an authenticated dockerhub account and I receive the below error. 

Error:
```
output | WARN: (exporting outputs) authorization status: 401: authorization failed
Share your logs with an Earthly account (experimental)! Register for one at https://ci.earthly.dev./
Error: build target: build main: failed to solve: authorization status: 401: authorization failed
```
Sucessful Login:
```
Run docker login --username "$DOCKERHUB_USERNAME" -***
Authenticating with existing credentials...
Login Succeeded
```
Gitlab CI:
Basically the example from the docs
```
name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      FORCE_COLOR: 1
    steps:
    - uses: actions/checkout@v3
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
    - name: Download latest earthly
      run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.19/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
    - name: Earthly version
      run: earthly --version
    - name: Run build
      run: earthly --ci --push +build
```

Earthfile Save Image line:

Belongs to the authorised docker account, completes without push
```
    SAVE IMAGE --push oddiesea/bun:latest
```

**Comment by adamgordonbell** [comment]
Hi @Oddiesea,

The way you are doing this looks correct to me. Does it work if you do the push with docker. Something like:
```
name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      FORCE_COLOR: 1
    steps:
    - uses: actions/checkout@v3
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
    - name: Download latest earthly
      run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.19/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
      run: |- 
          earthly  +build
          docker push oddiesea/bun:latest
```
