### ISSUE TITLE
Running multiple jobs in parallel causes race conditions for buildkit startup

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#2194]
Earthly automatically starts up the buildkit daemon if it's not already started. But if two jobs attempt to do this at the same time, the following occurs.

```
docker: Error response from daemon: Conflict. The container name "/earthly-buildkitd" is already in use by container "5bd39c324493f9ca2745b846d8827d70410c8ae9f9ec486a86f61f184bcda740". You have to remove (or rename) that container to be able to reuse that name.
```

We need to make this startup resilient to such race conditions. Given that this is the local machine, perhaps a file-based lock is all we need.

**Comment by kcampion** [comment]
I returned this mistake in your Slack. The goal is to launch 2 jobs in parallel under GitLab CI.

I used this .gitlab-ci.yml
```
image: docker:git

services:
  - docker:dind

before_script:
  - apk update
  - wget https://github.com/earthly/earthly/releases/download/v0.6.22/earthly-linux-amd64 -O /usr/local/bin/earthly
  - chmod +x /usr/local/bin/earthly
  - export FORCE_COLOR=1
  - /usr/local/bin/earthly bootstrap

stages:
  - build

build-api:
  stage: build
  script:
    - earthly --ci +build-api

build-front:
  stage: build
  script:
    - earthly --ci +build-front
```
