### ISSUE TITLE
Support automatic per-project configuration files

### ISSUE THREAD

**Issue by bbugh** [earthly/earthly#2208]
## Summary

1. We have some configurations (like that we want to share across the team without needing to customize everyone's global earthly configs, particularly for less tech support for our less technically-adept team members.

2. I'm working on a side project where I've implemented Earthly, and the `earthly` command always tries to use our organization's satellite, which I constantly forget to disable. 

## Proposal

The `--config` option exists, but it would be much more convenient to have earthly automatically search the local folder and up the tree for `earthly.config.yml` or some equivalent file, like many other tools do. (I don't know if there's a Go equivalent of [cosmiconfig](https://www.npmjs.com/package/cosmiconfig) but that would make it easy!)

It would need to merge the local configs with the global, so we can still customize our global cache sizes for those of us with 512GB vs 8TB drives.

I imagine this would also need to have a `--local` and `--global` flag for `earthly config`, like `git` and `bundler`, etc.

## Example

```yaml
# ~/.earthly/config
global:
    cache_size_mb: 64000
    cache_size_pct: 50
```

```yaml
# our_project/earthly.config.yaml
config:
    secret_provider: my-secret-provider
satellite:
    name: our-satellite
    org: our-org
```

This local file would also be used by subfolders:

```bash
/our_project/client-apps » earthly +whatever # uses ../earthly.config.yaml + global
```

The merged result for running the `earthly` command in this scenario would be:

```yaml
global:
    cache_size_mb: 64000
    cache_size_pct: 50
config:
    secret_provider: my-secret-provider
satellite:
    name: our-satellite
    org: our-org
```
