### ISSUE TITLE
Add support for updating Earthly `FROM` with Dependabot

### ISSUE THREAD

**Issue by shepherdjerred** [earthly/earthly#2213]
Dependabot makes it incredibly easy to keep things up-to-date, and it integrates well with GitHub. It would be fantastic if Earthfiles could be updated by Dependabot, so that when new base images come out a PR is automatically opened to update my Earthfiles.

**Comment by vinayakj02** [comment]
For Dockerfiles this can be done with a dependabot.yml like this, Will the same work for Earthfiles ? 

```
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
```
