### ISSUE TITLE
Allow creation of shared docker network across multiple compose files

### ISSUE THREAD

**Issue by EamonKeane** [earthly/earthly#2482]
Great project!

I came across a use case that I couldn't manage to get working. I have two tightly coupled projects and I want to re-use the logic around creating a mysql database that is only in one of the docker compose files.

The syntax for creating the networks is as shown below.

compose file 1
```
version: '3.9'

networks:
  default:
    name: my-db-net (gets auto-created by docker if not present)
```

compose file 2

```
version: '3.9'

networks:
  default:
    name: my-db-net
    external: true
```

```  
WITH DOCKER \
      --compose docker-compose1.yml \
     --compose docker-compose2.yml
```

As far as I can tell, earthly's `WITH DOCKER` block loads each of the compose files in parallel, and thus the second compose file fails because the external network has not been created yet. As potential options, the ability to create a network before running the compose files, or to allow ordering of the compose file creation would help address this.
