### ISSUE TITLE
Git URL is malformed when using `substitute`

### ISSUE THREAD

**Issue by serverwentdown** [earthly/earthly#2662]
https://github.com/earthly/earthly/blob/407195175ac31835f221cfdba1f807cd8eeed084/buildcontext/gitlookup.go#L650

`gitPath` has no proceeding slashes, so the URL ends up as `github.comearthly/earthly`

```yaml
git:
  "github.com":
    auth: https
    pattern: "github.com/(.+)"
    substitute: "https://example.com/$1.git"
```
