### ISSUE TITLE
gitlab CI example is wrong and doesn't allow configuring registry mirrors

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#3383]
**What is wrong?**
https://docs.earthly.dev/ci-integration/vendor-specific-guides/gitlab-integration is wrong

**Why?**
the earthly-entrypoint.sh script starts buildkitd directly; there's no need to run `bootstrap` manually.

Furthermore the entrypoint runs `buildkitd --config=/etc/buildkitd.toml` without applying any of the earthly config what's specified via `GLOBAL_CONFIG`.

there's absolutely no way to configure buildkitd.toml before it starts up.

**Comment by alexcb** [comment]
so the trick to getting this done is by setting `EARTHLY_ADDITIONAL_BUILDKIT_CONFIG`, e.g.

```
services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  FORCE_COLOR: 1
  EARTHLY_EXEC_CMD: "/bin/sh"
  EARTHLY_ADDITIONAL_BUILDKIT_CONFIG: |-
    [registry."docker.io"]
      mirrors = ["example.registry.dev"]

image: earthly/earthly:v0.7.20

before_script:
    - ps auxw
    - sleep 30
    - ps auxw # by this point buildkitd will have started up
    - cat /etc/buildkitd.toml || true # this should should EARTHLY_ADDITIONAL_BUILDKIT_CONFIG was correctly applied
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

earthly:
  stage: build
  script:
    - earthly --ci --push -P +build
    - ps auxw
    - cat /etc/buildkitd.toml || true
```

however the gitlab-integration should still never run bootstrap directly.

**Comment by alexcb** [comment]
TODO: we should expand the docs to show how to configure a mirror.

**Comment by alexcb** [comment]
example screenshot of the script output, which might help debugging the `EARTHLY_ADDITIONAL_BUILDKIT_CONFIG` is set correctly.
![image](https://github.com/earthly/earthly/assets/1806823/3cc19d9f-a7ca-4dc1-8830-6bb3f5eb80d4)

**Comment by brettdh** [comment]
More generally, the problem here is that the `earthly/earthly` docker image doesn't apply `global.buildkit_additional_args` or `global.buildkit_additional_config` from the loaded Earthly config, whether it comes from `GLOBAL_CONFIG` or `/etc/.earthly/config.yml` on disk.

I'd suggest that the scope of this issue be broadened beyond Gitlab; it's an issue that affects any environment that uses the `earthly/earthly` docker image.

**Comment by brettdh** [comment]
Also, I'm not sure what TOML parser is being used here, but AFAICT, these examples should all be equivalent:

```toml
[registry."foo.example.com"]
ca=["/path/to/ca.crt"]
```

```toml
registry."foo.example.com" = {ca = ["/path/to/ca.crt"]}
```

```toml
registry."foo.example.com".ca = ["/path/to/ca.crt"]
```

```toml
registry = {"foo.example.com" = {ca = ["/path/to/ca.crt"]}}
```

However, the first one is the only one that causes buildkitd to use the provided CA cert, and it's proving difficult to shove a newline in an environment variable in my CI environment (Bamboo).
