### ISSUE TITLE
Per-site git options should support a custom `GIT_SSH_COMMAND`

### ISSUE THREAD

**Issue by weaversam8** [earthly/earthly#3499]
I encountered an issue cloning a repository with an RSA key in my ssh-agent, because the alpine git image used for cloning doesn't allow rsa keys by default. I fix this on my local machine with a `PubkeyAcceptedKeyTypes +ssh-rsa` in my SSH config for that site.

It would be ideal if you could specify a value for the `GIT_SSH_COMMAND` environment variable, to allow the user to specify custom SSH options like this. It could look something like this:

```
git:
    git.example.com:
        auth: ssh
        user: git
        ssh_command: "ssh -o 'PubKeyAcceptedKeyTypes +ssh-rsa'"
```

and then the value of the `ssh_command` YAML key could be passed into the git image as `GIT_SSH_COMMAND`.
