### ISSUE TITLE
[Question] Earthly in Azure DevOps.

### ISSUE THREAD

**Issue by DraqunTheWorker** [earthly/earthly#3824]
Hey. I would like to use Earthly in Azure DevOps. Unfortunately, I can't for the life of me configure the pipeline so that it works. Could someone perhaps manage to configure it and share the solution with me?

This solution causes the pipeline to fail on initialization.
```yml
trigger:
  branches:
    include:
      - '*'

resources:
  containers:
    - container: earthly
      image: "earthly/earthly"
      options: --user root

stages:
- stage: PreBuild
  jobs:
    - job: SayHello
      container: earthly
      steps:
        - script: |
            earthly say-hello
```

The following solution, on the other hand, results in the following error: Error: could not determine buildkit address - is Docker or Podman running?
```yml
- job: SayHello
      displayName: 'Say hello'
      steps:
        - script: |
            docker pull earthly/earthly:latest
            docker run --rm -e NO_BUILDKIT=${NO_BUILDKIT} -v "${PWD}":/app -w /app earthly/earthly --verbose +say-hello
```

Any help will be appreciated.
Best regards.
Draqun
