### ISSUE TITLE
Proposal: Heredoc and inline files

### ISSUE THREAD

**Issue by vladaionescu** [earthly/earthly#582]
Allow long commands to be specified as [heredoc](https://en.wikipedia.org/wiki/Here_document).

Similarly, allow files to be specified inline via heredoc.

### Example heredoc command

```
some-target:
  RUN <<EOF
    echo "Downloading something"
    curl -o ./file -L https://...
    chmod +x ./file
  EOF
```

### Example heredoc file

```
some-target:
  COPY - ./docker-compose.yml <<EOF
  version: "3"
  
  services:
    postgres:
      image: aa8y/postgres-dataset:iso3166
      ports:
        - 127.0.0.1:5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
  EOF
```

### Notes

* The text needs to be indented if it's part of a non-base target. Otherwise the text is interpreted as raw - eg cannot use comments, variables are not expanded.
