### ISSUE TITLE
disallow locally/privileged execution of non-trusted sources

### ISSUE THREAD

**Issue by alexcb** [earthly/earthly#927]
Earthly can build from a remote target, e.g. `earthly github.com/earthly/earthly:main+for-linux`; however with the addition of the `LOCALLY` directive (and `--privileged` RUN flag), we should disallow execution from remote targets unless a user explicitly lists a repo as being trusted.

We currently have a PR to deny these under https://github.com/earthly/earthly/pull/926 but need to come up with the trusted list to allow users who require remote privileged commands to run.

Here's an idea for extending our `~/.earthly/config.yml` config:
```yaml
git:
    myserver:
        pattern: myserver/([^/]+)
        substitute: ssh://root@server:2222/root/my/really/weird/path/$1.git
        auth: ssh
    company:
        pattern: git.company.com/([^/]+)/([^/]+)
        substitute: ssh://git@git.company.com:22/var/company-code/$1/$2.git
        auth: ssh
trusted:
    # a specific repo
  - github.com/earthly/earthly
    # or an entire org
  - github.com/alexcb
    # it should work with custom repos too:
  - myserver/project
    # or an entire custom repo host:
  - git.company.com
```

note that the trusted repos do not end with a slash; this is intentional, we will implicitly add a slash after these. This is to prevent a case where you list `github.com/earthly` and forget to add a trailing slash which would then unintentionally trust other repos with the same prefix (e.g. `github.com/earthlygems`).
